// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfbpii2_v-9EV02TOFYpay_OBonulcZWg',
    appId: '1:943290372223:web:9e51a03c57998f96742f4a',
    messagingSenderId: '943290372223',
    projectId: 'ticketappx',
    authDomain: 'ticketappx.firebaseapp.com',
    storageBucket: 'ticketappx.firebasestorage.app',
    measurementId: 'G-XKME0NZZDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqiKHCChNUNboXqIFmVqm6YyW78blZRsE',
    appId: '1:943290372223:android:eb19c635ee935adf742f4a',
    messagingSenderId: '943290372223',
    projectId: 'ticketappx',
    storageBucket: 'ticketappx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9qi4HuOOCf6exqy-eCM5CWxCHLpzWTX8',
    appId: '1:943290372223:ios:af59d85060c1bbae742f4a',
    messagingSenderId: '943290372223',
    projectId: 'ticketappx',
    storageBucket: 'ticketappx.firebasestorage.app',
    iosClientId: '943290372223-sr47gbua43qa2sqo6dq35nbn0m17amgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.ticketApp',
  );
}
